language: c
matrix:
  include:
    - compiler: gcc
      os: linux
      env: EXTRA=--enable-werror
    - compiler: gcc
      os: linux
      arch: arm64-graviton2
      virt: lxd
      group: edge
      env: EXTRA=--enable-werror
    - compiler: clang
      os: linux
    - compiler: clang
      os: linux
      arch: arm64-graviton2
      virt: lxd
      group: edge
    - compiler: gcc
      os: linux
      arch: amd64
      addons:
        apt:
          packages:
          - libtool
    - compiler: gcc
      os: linux
      arch: arm64-graviton2
      virt: lxd
      group: edge
      addons:
        apt:
          packages:
          - libtool

script:
 - ./autogen.sh
 - ./configure $EXTRA
 - make
 - cd .libs
 - if [[ $TRAVIS_OS_NAME == linux ]]; then LD_LIBRARY_PATH=. && export LD_LIBRARY_PATH ; fi
 - if [[ $TRAVIS_OS_NAME == osx ]]; then DYLD_LIBRARY_PATH=. && export DYLD_LIBRARY_PATH ; fi
 - ./admesh ../block.stl
